/* Generated by Yosys 0.6 (git sha1 UNKNOWN, clang 3.4-1ubuntu3 -fPIC -Os) */

module D_FF(D, clk, rst, q);
  wire _0_;
  input D;
  input clk;
  output q;
  input rst;
  AND2X2 _1_ (
    .A(D),
    .B(rst),
    .Y(_0_)
  );
  DFFPOSX1 _2_ (
    .CLK(clk),
    .D(_0_),
    .Q(q)
  );
endmodule

module RtoR(clk, rst, a, b, f);
  input a;
  input b;
  input clk;
  wire comb2;
  output f;
  wire inva;
  wire q;
  input rst;
  INVX1 _0_ (
    .A(a),
    .Y(inva)
  );
  NAND2X1 _1_ (
    .A(q),
    .B(b),
    .Y(comb2)
  );
  D_FF dff1 (
    .D(inva),
    .clk(clk),
    .q(q),
    .rst(rst)
  );
  D_FF dff2 (
    .D(comb2),
    .clk(clk),
    .q(f),
    .rst(rst)
  );
endmodule
